on:
  push:
    branches-ignore:
      - develop

name: Code Checks (run on all but develop branches)
jobs:
  checkChangelog:
    name: Check CHANGELOG
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch origin
        if sh -c "git diff origin/develop --exit-code CHANGELOG.md"; then
            echo "CHANGELOG.md wasn't changed, failing!"
            exit 255 
        else
            exit_code=$?
            echo "CHANGELOG.md was changed, passing!"
            exit 0
        fi

